# Generated by Django 4.1.4 on 2022-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearRegressionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('model', models.TextField()),
            ],
        ),
    ]
