name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Check Python version
        run: python --version

      - name: Install Dependencies (Linear Regression - FastAPI)
        working-directory: ./algorithms/linear-regression/fastapi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Linear Regression - FastAPI)
        working-directory: ./algorithms/linear-regression/fastapi
        run: |
          pytest tests.py
